### ISSUE TITLE
worker is not working on Java 1.8

### ISSUE THREAD

**Issue by mindreframer** [wildbit/mysql-queue#2]
```
$ java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```

also the tests seem to fail... 

```
Testing mysql-queue.core-test

FAIL in (job-processing-test) (core_test.clj:68)
Failed to process 100 test jobs in 10 seconds.
Missing job IDs: #{65 70 62 74 7 59 86 20 72 58 60 27 1 69 24 55 85 39 88 46 4 77 95 54 92 15 48 50 75 99 21 31 32 40 91 56 33 13 22 90 36 41 89 100 43 61 29 44 93 6 28 64 51 25 34 17 3 12 2 66 23 47 35 82 76 97 19 57 68 11 9 5 83 14 45 53 78 26 16 81 79 38 98 87 30 73 96 10 18 52 67 71 42 80 37 63 94 8 49 84}
Exception?: nope

expected: (deref success? 10000 false)
  actual: (not (deref #<core$promise$reify__6363@6296c184: :pending> 10000 false))

FAIL in (job-processing-test) (core_test.clj:69)
The number of executed jobs doesn't match the number of jobs queued.

expected: 100
  actual: 0

expected: 0 to be an instance of java.lang.Long
     was: 0 is an instance of java.lang.Integer

FAIL in (parallel-job-processing-test) (core_test.clj:94)
Failed to process 100 test jobs in 15 seconds.
Missing job IDs: #{65 70 62 74 7 59 86 20 72 58 60 27 1 69 24 55 85 39 88 46 4 77 95 54 92 15 48 50 75 99 21 31 32 40 91 56 33 13 22 90 36 41 89 100 43 61 29 44 93 6 28 64 51 25 34 17 3 12 2 66 23 47 35 82 76 97 19 57 68 11 9 5 83 14 45 53 78 26 16 81 79 38 98 87 30 73 96 10 18 52 67 71 42 80 37 63 94 8 49 84}
Exception?: nope

expected: (deref success? 15000 false)
  actual: (not (deref #<core$promise$reify__6363@79f14c56: :pending> 15000 false))

FAIL in (parallel-job-processing-test) (core_test.clj:95)
The number of executed jobs doesn't match the number of jobs queued.

expected: 100
  actual: 0

expected: 0 to be an instance of java.lang.Long
     was: 0 is an instance of java.lang.Integer

FAIL in (stuck-job-processing-test) (core_test.clj:154)
Failed to process 100 test jobs in 15 seconds.
Missing job IDs: #{65 70 62 74 7 59 86 20 72 58 60 27 1 69 24 55 85 39 88 46 4 77 95 54 92 15 48 50 75 99 21 31 32 40 91 56 33 13 22 90 36 41 89 100 43 61 29 44 93 6 28 64 51 25 34 17 3 12 2 66 23 47 35 82 76 97 19 57 68 11 9 5 83 14 45 53 78 26 16 81 79 38 98 87 30 73 96 10 18 52 67 71 42 80 37 63 94 8 49 84}
Exception?: nope

expected: (deref success? 15000 false)
  actual: (not (deref #<core$promise$reify__6363@40a1916d: :pending> 15000 false))

FAIL in (stuck-job-processing-test) (core_test.clj:155)
The number of executed jobs doesn't match the number of jobs queued.

expected: 100
  actual: 0

expected: 0 to be an instance of java.lang.Long
     was: 0 is an instance of java.lang.Integer

FAIL in (graceful-shutdown-test) (core_test.clj:182)
Failed to finish 2 test jobs taking 1500ms with 2s quit timeout.
Missing job IDs: #{1 2}
Exception?: nope

expected: (deref success? 10 false)
  actual: (not (deref #<core$promise$reify__6363@1181a376: :pending> 10 false))

FAIL in (graceful-shutdown-test) (core_test.clj:183)
The number of executed jobs doesn't match the number of jobs queued.

expected: 2
  actual: 0

expected: 0 to be an instance of java.lang.Long
     was: 0 is an instance of java.lang.Integer

FAIL in (distributed-job-processing-test) (core_test.clj:127)
Failed to process 100 test jobs in 15 seconds.
Missing job IDs: #{65 70 62 74 7 59 86 20 72 58 60 27 1 69 24 55 85 39 88 46 4 77 95 54 92 15 48 50 75 99 21 31 32 40 91 56 33 13 22 90 36 41 89 100 43 61 29 44 93 6 28 64 51 25 34 17 3 12 2 66 23 47 35 82 76 97 19 57 68 11 9 5 83 14 45 53 78 26 16 81 79 38 98 87 30 73 96 10 18 52 67 71 42 80 37 63 94 8 49 84}
Exception?: nope

expected: (deref success? 15000 false)
  actual: (not (deref #<core$promise$reify__6363@75acb326: :pending> 15000 false))

FAIL in (distributed-job-processing-test) (core_test.clj:128)
The number of executed jobs doesn't match the number of jobs queued.

expected: 100
  actual: 0

expected: 0 to be an instance of java.lang.Long
     was: 0 is an instance of java.lang.Integer

Ran 5 tests containing 10 assertions.
10 failures, 0 errors.
Tests failed.
```

**Comment by temochka** [comment]
Hi! The tests seem to pass on Java 1.8 on both Travis (Oracle JDK 1.8) and my local machine (OpenJDK 8). Anything particular about your setup? Did you [create the test database](https://github.com/wildbit/mysql-queue/blob/master/.travis.yml#L9) before running the test suite?

**Comment by mindreframer** [comment]
Hi @temochka, thx for responding! 

Well, I have a mac book (10.11.1 (15B42)) ... Maybe that is reason.. 
Yes, I did create the test database.... 

Just reran the tests, lots of warnings and: 

```
Ran 5 tests containing 10 assertions.
10 failures, 0 errors.
Tests failed.
```

Also lots of warnings ... 

```

WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
```

So... not sure what else I should change.... 

I also ended up using a different library... (https://github.com/layerware/pgqueue/), it does not have a scheduler... but it works as advertised. 

If you guys are all on Linux and it works for you, then that is it. ))) 

Thx for the other open source projects, nice work! 

Best, Roman

**Comment by temochka** [comment]
Ok, thanks for additional information! I just ran the tests again on my MacBook Pro 2013 with OS X 10.11.6 (15G31) and Oracle Java 1.8.0_102 against MySQL Server 5.7.13 running on a Ubuntu 16.04 VM. I did encounter _one_ test failure, but it was caused by a too restrictive time constraint in the test itself. This is now fixed in 2d21db7feb5ff52e8963b82295785467b60aebda in the `master` branch.

I didn’t see any warnings, but searching that message on the web seems to indicate that they’re coming from JDBC. I added a possible fix in a67d607bb7b3e2565bc6281976bdec1d8ca7e9e7.

I’m going to close this issue as "unable to reproduce" soon unless you (or anybody else) can provide any further details.

I’ve seen [layerware/pgqueue](https://github.com/layerware/pgqueue/) before, and it seems like a nice solution for PostgreSQL. I’m glad it worked well for you.

**Comment by mindreframer** [comment]
@temochka thx! 
The fix for SSL warnings is working, that's cool! 

But still not job processing... 

In REPL the worker has "running" status, but no jobs are deleted from the queue

``` clojure
user=> worker
#mysql_queue.core.Worker
{:consumer-threads [#<clojure.core.async.impl.channels.ManyToManyChannel@1ac753bf>
                    #<clojure.core.async.impl.channels.ManyToManyChannel@1da114e3>],
 :db-conn {:password "",
           :subname "//localhost:3306/clj_mysql_queue?useSSL=false",
           :subprotocol "mysql",
           :user "root"},
 :input-chan #<clojure.core.async.impl.channels.ManyToManyChannel@310cf391>,
 :options {:buffer-size 10,
           :err-fn #<Fn@6a20533a mysql_queue.core/quiet_err_fn[fn]>,
           :log-fn #<Fn@4adabf6a mysql_queue.core/quiet_log_fn[fn]>,
           :max-scheduler-sleep-interval 10,
           :min-scheduler-sleep-interval 0,
           :num-consumer-threads 2,
           :prefetch 10,
           :recovery-threshold-mins 20},
 :recovery-thread #<clojure.core.async.impl.channels.ManyToManyChannel@5f49bcde>,
 :scheduler-thread #<clojure.core.async.impl.channels.ManyToManyChannel@90f4cdd>,
 :status #<Atom@7ee0a5eb :running>}
```

Jobs in the table.... 

``` mysql
| 1709 | my-job   | begin  | {:echo "Hello, world!"} | 2016-08-24 21:22:03 | 2016-08-24 21:22:03 |
| 1710 | my-job   | begin  | {:echo "Hello, world!"} | 2016-08-24 21:23:16 | 2016-08-24 21:23:16 |
| 1711 | my-job   | begin  | {:echo "Hello, world!"} | 2016-08-24 21:26:31 | 2016-08-24 21:26:31 |
| 1712 | my-job   | begin  | {:echo "Hello, world!"} | 2016-08-24 21:27:45 | 2016-08-24 21:27:45 |
+------+----------+--------+-------------------------+---------------------+---------------------+
```

But well, I understand, that it is outside of your reach to fix (without my computer at hand, hehe)...

Thx and lets hope that this is only broken for me alone! 

Best, 
Roman

**Comment by temochka** [comment]
Yeah, unfortunately there isn’t much I can work with here. If you’d like to help me debug this issue, here’re a few things:
- Look at one failing test at a time. For example, `job-processing-test`. You can run only this test by using the `lein test :only mysql-queue.core-test/job-processing-test` command (or from the REPL).
- [Pass an actual logging function](https://github.com/wildbit/mysql-queue/blob/master/test/mysql_queue/core_test.clj#L62) (for example, `:log-fn println`) to the worker "constructor". This will result in a _very_ verbose output, so also reduce `num-jobs` (try 1,5,10, etc.).

Here’s the output produced by running this one test with 1 published job on my machine:

``` bash
$ lein test :only mysql-queue.core-test/job-processing-test

lein test mysql-queue.core-test
:info nil Starting a new worker...
:debug nil Published 1 new jobs.
:debug #mysql_queue.core.ScheduledJob{:user-fn #<core_test$fn__8930$fn__8932 mysql_queue.core_test$fn__8930$fn__8932@5b0b1aba>, :id 503, :name :test-foo, :status :begin, :parameters {:id 1}, :due-at #inst "2016-08-24T19:53:45.000000000-00:00"} Consumer received job ScheduledJob[503:test-foo:begin]
:info #mysql_queue.core.ScheduledJob{:user-fn #<core_test$fn__8930$fn__8932 mysql_queue.core_test$fn__8930$fn__8932@5b0b1aba>, :id 503, :name :test-foo, :status :begin, :parameters {:id 1}, :due-at #inst "2016-08-24T19:53:45.000000000-00:00"} Executing job ScheduledJob[503:test-foo:begin]
:debug #mysql_queue.core.Job{:user-fn #<core_test$fn__8930$fn__8932 mysql_queue.core_test$fn__8930$fn__8932@5b0b1aba>, :id 1275, :scheduled-job-id 503, :parent-id 0, :name :test-foo, :status :begin, :parameters {:id 1}, :attempt 1} Consumer received job Job[1275:test-foo:begin]
:info #mysql_queue.core.Job{:user-fn #<core_test$fn__8930$fn__8932 mysql_queue.core_test$fn__8930$fn__8932@5b0b1aba>, :id 1275, :scheduled-job-id 503, :parent-id 0, :name :test-foo, :status :begin, :parameters
{:id 1}, :attempt 1} Executing job Job[1275:test-foo:begin]
:debug #mysql_queue.core.Job{:user-fn #<core_test$fn__8930$fn__8932 mysql_queue.core_test$fn__8930$fn__8932@5b0b1aba>, :id 1276, :scheduled-job-id 503, :parent-id 1275, :name :test-foo, :status :done, :parameters {:id 1}, :attempt 1} Consumer received job Job[1276:test-foo:done]
:debug Consumer Thread Consumer is stopping...
:debug nil Publisher is stopping...
:debug nil Publisher is stopping...

Ran 1 tests containing 2 assertions.
0 failures, 0 errors.
```

If you don’t have time to look into this, I understand. I have plans to add benchmarks and stress tests to this library at some point. Maybe they’ll reveal this problem. Though we’ve been running it in production for about a year now with no known issues (it was extracted from our [DMARC digests app](https://dmarc.postmarkapp.com)).

**Comment by mindreframer** [comment]
Here is the output... Unfortunately the logging fn is not working, what should I change? 

``` clojure
(deftest job-processing-test
  (let [num-jobs 5
        expected-set (->> num-jobs range (map inc) (into #{}))
        success? (promise)
        exception (promise)
        check-ins (check-in-atom expected-set success?)
        jobs {:test-foo (fn [status {id :id :as args}]
                          (Thread/sleep 10)
                          (swap! check-ins conj id)
                          [:done args])}
        _ (dotimes [n num-jobs]
            (schedule-job db-conn :test-foo :begin {:id (inc n)} (java.util.Date.)))]
    (with-worker [wrk (worker db-conn
                              jobs
                              :num-consumer-threads 1
                              :err-fn #(deliver exception %)
                              :log-fn println
                              :max-scheduler-sleep-interval 0.5
                              :max-recovery-sleep-interval 0.5)]
      (is (deref success? 15000 false)
          (str "Failed to process " num-jobs " test jobs in 15 seconds.\n"
               "Missing job IDs: " (clj-set/difference expected-set @check-ins) "\n"
               "Exception?: " (deref exception 0 "nope")))
      (is (= num-jobs (count @check-ins))
          "The number of executed jobs doesn't match the number of jobs queued."))))

```

``` clojure
Testing mysql-queue.core-test
:info nil Starting a new worker...

FAIL in (job-processing-test) (core_test.clj:66)
Failed to process 5 test jobs in 15 seconds.
Missing job IDs: #{1 4 3 2 5}
Exception?: nope

expected: (deref success? 15000 false)
  actual: (not (deref #<clojure.core$promise$reify__7005@2258228f pending> 15000 false))

FAIL in (job-processing-test) (core_test.clj:70)
The number of executed jobs doesn't match the number of jobs queued.

expected: 5
  actual: 0

expected: 0 to be an instance of java.lang.Long
     was: 0 is an instance of java.lang.Integer
       :debug Consumer Thread Consumer is stopping...
:debug:debug  nilnil  Publisher is stopping...Publisher is stopping...


Ran 1 tests containing 2 assertions.
2 failures, 0 errors.
Tests failed.
```

**Comment by temochka** [comment]
That’s still helpful, thanks! The logging function actually seems to be working fine (I see some info and debug output in your logs). The absence of any actual work being done is still a concern 😃  It looks like the publisher never recognizes any jobs as pending. You’re saying they do appear in MySQL though? If that’s the case, I think I know what it is and why I never saw it: ...Because you and I are on the different side of UTC! It’s not documented (and even I forgot about this), but the scheduler [always works in UTC](https://github.com/wildbit/mysql-queue/blob/master/src/mysql_queue/queries.clj#L73). Our servers are all UTC. My local machine is not UTC (EDT), but it’s behind UTC, so any created job is immediately pending. Travis, too, is either UTC or one of the US time zones.

You can verify if this is the issue by setting your JVM timezone to UTC. In `project.clj`, please specify `:jvm-opts  ["-Duser.timezone=UTC"]`. I was now able to reproduce this issue by using `:jvm-opts  ["-Duser.timezone=Europe/Berlin"]`. I created a separate issue #3 for that. Please let me know if using UTC fixes this bug in your case though.

**Comment by mindreframer** [comment]
CRAZYYYY! that was it! 

Тёмочка! Никогда бы не догадался! Круто! Спасибо большое! Может еще переделаю мой велосипед  и костыли на mysql-queue.. 

Very-very-very nice work! )))

Good night wherever you are! (It is night now here in Berlin...)
Roman

**Comment by temochka** [comment]
Haha, I was glad to help :) As someone wiser than me (must have) said once: "Timezones strike when you least expect it."

Спасибо и доброй ночи :) Привет вашим велосипедам от наших! И костылям привет 👍

Thanks again for your help debugging this issue. And we can do better than just failing to work properly in non-UTC timezones :) Fixing #3 will be a good first step. Good night!
